version: '3.6'

services:

  discuss_app:
    build:
      context: .
      dockerfile: Dockerfile-with-compose
    ports:
      - 4000:4000
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_URL=discuss_db
    depends_on:
      - discuss_db

  discuss_db:
    build:
      context: .
      dockerfile: Dockerfile-db-with-compose
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
