FROM elixir:1.8.1-alpine

WORKDIR /usr/src/app

COPY . .

RUN apk add npm && \
    npm install

RUN apk add inotify-tools && \
    mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new-1.2.5.ez && \
    mix deps.get
    
RUN mix compile

RUN chmod +x entrypoint.sh

CMD ["/usr/src/app/entrypoint.sh"]
